version: '3'
services:

  db:
    image: mariadb:latest
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_db_password
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=ghost_db_password
      - MYSQL_DATABASE=ghost_production
    volumes:
      - ./data/dbdata:/var/lib/mysql

  ghost:
    image: ghost:alpine
    container_name: ghost
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "<port>:2368"
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: ghost_db_password
      database__connection__database: ghost_production
      url: http://<domain>:<port>
    volumes:
      - ./content:/var/lib/ghost/content
   