version: '3'
services:

  ghost:
    image: ghost:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      url: https://<domain>
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: MyStrongPassword
      database__connection__database: ghost
    volumes:
        - ./content:/var/lib/ghost/content
        - ./config.production.json:/var/lib/ghost/config.production.json
        
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    restart: always
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD= MyStrongPassword
    volumes:
      - ./data/dbdata:/var/lib/mysql

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - ghost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /usr/share/nginx/html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
